[build]
command = "npx expo export --platform web"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# Fallback SPA: todas las rutas a index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
